
spring: 

    datasource: 
        url: jdbc:mysql://127.0.0.1:3307/laf?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        
    mybatis:
        typeAliasesPackage: com.test.pojo
        mapperLocations: classpath:mappers/*.xml
    mvc:
        view:
          prefix: templates/
          suffix: .html
    thymeleaf:
        cache:  false
server: 
  port: 8080
  